build_bitmaps:
    BITMAP "........"
    BITMAP "X.X.X.X."
    BITMAP "XXXXXXX."
    BITMAP ".XXXXX.."
    BITMAP ".XXXXX.."
    BITMAP ".XXXXX.."
    BITMAP ".XXXXX.."
    BITMAP ".XXXXX.."

    BITMAP "........"
    BITMAP "X.X..X.X"
    BITMAP "X.X..X.X"
    BITMAP "X.X..X.X"
    BITMAP "XXXXXXXX"
    BITMAP "X.XXXX.X"
    BITMAP "XXXXXXXX"
    BITMAP "XXX..XXX"

	BITMAP "........"
	BITMAP "X.X.X.X."
	BITMAP ".X...X.."
	BITMAP "XXXXXXXX"
	BITMAP "........"
	BITMAP "X.X.X.X."
	BITMAP ".X...X.."
	BITMAP "XXXXXXXX"

	BITMAP "........"
	BITMAP "XXXXXXXX"
	BITMAP "...XX..."
	BITMAP "..XXXX.."
	BITMAP "..XXXX.."
	BITMAP ".XXXXXX."
	BITMAP ".XXXXXX."
	BITMAP "XXXXXXXX"

	BITMAP "...XX..."
	BITMAP "...XX..."
	BITMAP "...XX..."
	BITMAP "XXXXXXXX"
	BITMAP "XXXXXXXX"
	BITMAP "...XX..."
	BITMAP "...XX..."
	BITMAP "...XX..."

	BITMAP "...XX..."
	BITMAP "..XXXX.."
	BITMAP ".XX..XX."
	BITMAP "XXXXXXXX"
	BITMAP "XXXXXXXX"
	BITMAP "X..XXXXX"
	BITMAP "X..XX.XX"
	BITMAP "XXXXX.XX"

	BITMAP "....XX.."
	BITMAP "....XX.."
	BITMAP "...X...X"
	BITMAP ".XXXXXX."
	BITMAP ".XX..X.."
	BITMAP "XXX.X..."
	BITMAP "..X....."
	BITMAP "..X....."

	BITMAP "........"
	BITMAP "........"
	BITMAP "....X..."
	BITMAP "...XXX.."
	BITMAP ".XXXXXXX"
	BITMAP "..XXXXX."
	BITMAP "........"
	BITMAP "........"

	BITMAP "........"
	BITMAP "..X....."
	BITMAP "..X....X"
	BITMAP "..XXX.X."
	BITMAP "XXXXXXXX"
	BITMAP "XXXXXXXX"
	BITMAP ".XXXXXX."
	BITMAP "........"