fishing_boat_death_anim_bitmaps:
    BITMAP "........"
    BITMAP "x....X.."
    BITMAP ".......x"
    BITMAP ".X.XXX.."
    BITMAP "XXXXXXXX"
    BITMAP ".XXXXXX."
    BITMAP "........"
    BITMAP "........"

    BITMAP "x.x....."
    BITMAP "......x."
    BITMAP ".x.x.x.x"
    BITMAP "........"
    BITMAP "XXXXXXXX"
    BITMAP ".XXXXXX."
    BITMAP "........"
    BITMAP "........"

    BITMAP "x.x....x"
    BITMAP "....x..."
    BITMAP ".x...x.."
    BITMAP "...x...."
    BITMAP "XX...XXX"
    BITMAP ".XXXXXX."
    BITMAP "........"
    BITMAP "........"

    BITMAP "x....x.."
    BITMAP "..x...x."
    BITMAP "........"
    BITMAP ".....xx."
    BITMAP "....xx.."
    BITMAP ".xxxxx.."
    BITMAP "........"
    BITMAP "........"

    BITMAP "........"
    BITMAP "........"
    BITMAP "........"
    BITMAP ".....x.."
    BITMAP "....xx.."
    BITMAP ".xxxx..."
    BITMAP "........"
    BITMAP "........"

CONST FISHING_BOAT_DEATH_ANIM_FINAL_INDEX = 4