    'color constants
    CONST BLACK = 0
    CONST BLUE = 1
    CONST RED = 2
    CONST TAN = 3
    CONST DARK_GREEN = 4
    CONST GREEN = 5
    CONST YELLOW = 6
    CONST WHITE = 7
    CONST GRAY = 8
    CONST CYAN = 9
    CONST ORANGE = 10
    CONST BROWN = 11
    CONST PINK = 12
    CONST LIGHT_BLUE = 13
    CONST YELLOW_GREEN = 14
    CONST PURPLE = 15
